name: Bug report
description: Create a report to help us improve
body:
- type: input
  attributes:
    label: PayPal SDK Version
    placeholder: "e.g. 1.19.0"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Environment
    options:
      - Sandbox
      - Live
      - Both
  validations:
    required: true
- type: input
  attributes:
    label: Xcode Version
    placeholder: "e.g. Xcode 14.3"
  validations:
    required: true
- type: input
  attributes:
    label: OS Version & Device
    placeholder: "e.g iPhone 14 - iOS 16.4"
  validations:
    required: false
- type: dropdown
  attributes:
    label: Integration type
    options:
      - Swfit Package Manager
      - CocoaPods
      - Other
  validations:
    required: true
- type: dropdown
  attributes:
    label: Development Processor
    options:
      - Intel
      - Apple Silicon (M-series chips)
      - Both
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: Description of what the bug is. Please include as many details as possible.
  validations:
    required: true
- type: textarea
  attributes:
    label: To reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: Description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    placeholder: |
      Do not reveal sensitive data. For example, credit card numbers & customer credentials.
  validations:
    required: false
