name: Build
on: [pull_request]
concurrency:
  group: build-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  cocoapods:
    name: CocoaPods
    runs-on: macOS-13
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Use Xcode 15.1
        run: sudo xcode-select -switch /Applications/Xcode_15.1.app
      - name: Run pod lib lint
        run: pod lib lint
  spm:
    name: Swift Package Manager
    runs-on: macOS-13
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Use Xcode 15.1
        run: sudo xcode-select -switch /Applications/Xcode_15.1.app
      - name: Use current branch
        run: sed -i '' 's/branch = .*/branch = \"'"${GITHUB_HEAD_REF//\//\/}"'\";/' SampleApps/SPMTest/SPMTest.xcodeproj/project.pbxproj
      - name: Run swift package resolve
        run: cd SampleApps/SPMTest && swift package resolve
      - name: Build & archive SPMTest
        run: xcodebuild -project 'SampleApps/SPMTest/SPMTest.xcodeproj' -scheme 'SPMTest' clean build archive CODE_SIGNING_ALLOWED=NO

